# -----------------------------------------------------------------------------
# Dotfiles Repo Specific Mise Configuration (global mise config is in `mise/config.toml`)
# -----------------------------------------------------------------------------

[tasks.default]
description = "Show available commands"
run = "mise tasks"
