## Atuin Configuration
## Full reference: https://docs.atuin.sh/configuration/config/

# Enable or disable automatic sync
auto_sync = true

# Enable of disable automatic update check
update_check = true

# How often to sync history, set to 0 to sync after every command
sync_frequency = "10m"

# which search mode to use, possible values are:
# prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

# which style to use
# possible values: auto, full, compact
style = "full"

# the maximum number of lines the interface should take up
# set it to 0 to always go full screen
inline_height = 40

enter_accept = true

## vim-mode
keymap_mode = "vim-insert"

## faster sync
[sync]
records = true

[theme]
name = "catppuccin-macchiato-lavender"