[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node", "ruby"]

[tools]
node = "lts"
go = "latest"
rust = "latest"
python = "3.12"
ruby = "3.4.6"
java = "21"
terraform = "latest"

[env]
MISE_ENV="global"
