[tool]
name = "zsh"
target = "~/.config/zsh"

[[link]]
src = "zshrc.tmpl"
dest = "~/.zshrc"

[[link]]
src = "zshenv"
dest = "~/.zshenv"

[[link]]
src = "zprofile"
dest = "~/.zprofile"

[[link]]
src = "lib"
dest = "~/.config/zsh"
