local parser_install_dir = vim.fn.stdpath("data") .. "/site"

vim.fn.mkdir(parser_install_dir, "p")
vim.opt.runtimepath:append(parser_install_dir)

require("nvim-treesitter.configs").setup({
  parser_install_dir = parser_install_dir,
  ensure_installed = {
    "astro",
    "bash",
    "bass",
    "chatito",
    "css",
    "csv",
    "desktop",
    "diff",
    "dockerfile",
    "editorconfig",
    "elixir",
    "eex",
    "fish",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "go",
    "gomod",
    "gosum",
    "gotmpl",
    "graphql",
    "helm",
    "html",
    "javascript",
    "jq",
    "json",
    "lua",
    "luadoc",
    "make",
    "pem",
    "prisma",
    "python",
    "ruby",
    "rust",
    "scss",
    "slim",
    "ssh_config",
    "svelte",
    "terraform",
    "tmux",
    "toml",
    "tsx",
    "typescript",
    "typespec",
    "typst",
    "vhs",
    "vim",
    "vimdoc",
    "yaml"
  },
  sync_install = false,
  auto_install = false,
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = false,
  },
  indent = {
    enable = true,
  },
  modules = {},
  ignore_install = {},
})
