[user]
email = "meagan.waller@gusto.com"

[git]
default_branch = "main"
sign_commits = true

[shells]
default = "zsh"

[paths]
work = "~/workspace"

[features]
copilot = true
work_proxy = true

[editor]
gui = "cursor"