#!/usr/bin/env sh

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Cache Homebrew prefix (avoid slow brew --prefix calls)
export HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-/opt/homebrew}"

export EDITOR="nvim"
export VISUAL="nvim"

export MANPAGER="less -X"

# Make some commands not show up in history
export HISTORY_IGNORE="(cd|cd *|ls|ls *|l|l *|ll|ll *|la|la *|brew|brew *|j|j *|z|z *|pwd|clear|exit|__|__*|*kraken*|*rainbow*)"

# Display time in History
export HISTTIMEFORMAT='%F %T '

# Cli COLOR
export CLICOLOR=1

# Coreutils
PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnuman:${MANPATH:-}"

# Localpath
PATH="$HOME/.local/bin:$PATH"

export PATH MANPATH

export DISABLE_TELEMETRY=1
export RESEND_TELEMETRY_DISABLED=1