[tool]
name = "bash"
target = "~"  # so .bashrc and .bash_profile end up in ~/

[[link]]
src = "bashrc.tmpl"
dest = "~/.bashrc"

[[link]]
src = "bash_profile.tmpl"
dest = "~/.bash_profile"

[[link]]
src = "bash_exports.tmpl"
dest = "~/.bash_exports"

[[link]]
src = "bash_aliases"
dest = "~/.bash_aliases"

[[link]]
src = "aliases"
dest = "~/.bash_aliases.d"
